#List of inputs that are regular plurals
regularplurals = [
	'house',
	'home',
	'alarm',
	'head',
	'temperature',
	'pie',
	'friend',
	'demigod',
	'book',
	'tea',
	'hippo',
	'chicken',
	'sun',
	'sunset',
	'sunrise',
	'watermelon',
	'rain',
	'cut',
	'nine',
	'explosion',
	'mosquito',
	'orange',
	'faucet',
	'girl',
	'boy',
	'hello',
	'kill',
	'mafia',
	'war',
	'catapult',
	'catastrophe',
	'goodbye',
	'train',
	'grammar',
	'rooster',
	'crayon',
	'trombone',
	'tuba',
	'dream',
	'meal',
	'history',
	'hurricane',
	'dolphin',
	'cheese',
	'thing',
	'apple',
	'brother',
	'sister',
	'flute',
	'hit',
	'marker',
	'bison',
	'science',
	'name',
	'bike',
	'bicycle',
	'night',
	'day',
	'volume',
	'satyr',
	'hole',
	'whole',
	'hammer',
	'wing',
	'shark',
	'ostrich',
	'dog',
	'burrito',
	'light',
	'eight',
	'note',
	'notebook',
	'sweater',
	'window',
	'song',
	'cello',
	'eye',
	'eyebrow',
	'pencil',
	'one',
	'sixteen',
	'nineteen',
	'eighteen',
	'million',
	'eleven',
	'thousand',
	'billion',
	'twelve',
	'seventeen',
	'fifteen',
	'fourteen',
	'hundred',
	'ten',
	'thirteen',
	'trillion',
	'blood',
	'back',
	'earth',
	'pen',
	'wizard',
	'cat',
	'squirrel',
	'brick',
	'pickaxe',
	'god',
	'human',
	'cow',
	'gram',
	'clock',
	'saxophone',
	'nail',
	'horse',
	'pig',
	'avacado',
	'violin',
	'viola',
	'fight',
	'fire',
	'finger',
	'fingernail',
	'mouth',
	'puddle',
	'word',
	'wand',
	'airplane',
	'seven',
	'hair',
	'five',
	'game',
	'bird',
	'flower',
	'price',
	'ocean',
	'sea',
	'bubble',
	'boat',
	'water',
	'duck',
	'sparkle',
	'zombie',
	'bee',
	'two',
	'butter',
	'want',
	'bread',
	'like',
	'need',
	'toe',
	'toenail',
	'clarinet',
	'turtle',
	'dinosaur',
	'four',
	'nose',
	'ninja',
	'dragon',
	'comment',
	'unicorn',
	'dance',
	'dancer',
	'pear',
	'fork',
	'spork',
	'tripod',
	'knife',
	'storm',
	'spoon',
	'base',
	'potato',
	'piano',
	'rabbit',
	'thunder',
	'bomb',
	'llama',
	'liter',
	'wall',
	'test',
	'quiz',
	'sequence',
	'three',
	'number',
	'trident',
	'peanut',
	'favorite',
	'car',
	'spy',
	'man',
	'banana',
	'spider',
	'trumpet',
	'star',
	'wind',
	'chair',
	'sword',
	'centaur',
	'noodle',
	'cake',
	'tree'
	]

#List of corresponding translations
trans = {
	'house': 'aba',
	'home': 'abel',
	'alarm': 'aghtiblaghti',
	'head': 'agucha',
	'temperature': 'aitholo',
	'pie': 'akinopala',
	'friend': 'ampinach',
	'demigod': 'antomisntra',
	'book': 'apsu',
	'tea': 'ashimye',
	'hippo': 'ayamhangri',
	'chicken': 'bakacha',
	'sun': 'bea',
	'sunset': 'beghom',
	'sunrise': 'bemogh',
	'watermelon': 'beodagmol',
	'rain': 'blupblup',
	'cut': 'boh',
	'nine': 'bontinpo',
	'explosion': 'byokamita',
	'mosquito': 'bzanch',
	'orange': 'camaneenah',
	'faucet': 'chabem',
	'girl': 'chaina',
	'boy': 'chaino',
	'hello': 'chichi',
	'kill': 'chickchak',
	'mafia': 'chickchickliluh',
	'war': 'chickchooth',
	'catapult': 'chikamezol',
	'catastrophe': 'chnacabaloom',
	'goodbye': 'chochu',
	'train': 'chuchupater',
	'grammar': 'cklyva',
	'rooster': 'coolah',
	'crayon': 'coramiti',
	'trombone': 'dalkanina',
	'tuba': 'darpuno',
	'dream': 'dohaka',
	'meal': 'dooble',
	'history': 'dotwisbfre',
	'hurricane': 'draggam',
	'dolphin': 'EEEEche',
	'cheese': 'eiso',
	'thing': 'etcha',
	'apple': 'fambonchink',
	'brother': 'fitamomo',
	'sister': 'fitolama',
	'flute': 'flambontic',
	'hit': 'floimre',
	'marker': 'gggancha',
	'bison': 'goomi',
	'science': 'gooooshhboom',
	'name': 'grchap',
	'bike': 'halkidel',
	'bicycle': 'halkidel',
	'night': 'hobegh',
	'day': 'hogbem',
	'volume': 'homucaifi',
	'satyr': 'hoooohaminto',
	'hole': 'hopel',
	'whole': 'hopooch',
	'hammer': 'huluch',
	'wing': 'ichamachafli',
	'shark': 'inscatery',
	'ostrich': 'jaacutin',
	'dog': 'jujuh',
	'burrito': 'kaama',
	'light': 'katawitawhota',
	'eight': 'kikolin',
	'note': 'kiml',
	'notebook': 'kimlaspu',
	'sweater': 'kiywart',
	'window': 'kolfamlo',
	'song': 'laleh',
	'cello': 'lamchlae',
	'eye': 'lampanicha',
	'eyebrow': 'lampanichataki',
	'pencil': 'latcolati',
	'one': 'lolk',
	'sixteen': 'lomant',
	'nineteen': 'lombon',
	'eighteen': 'lomkiko',
	'million': 'lomlito',
	'eleven': 'lomlo',
	'thousand': 'lomlot',
	'billion': 'lomloti',
	'twelve': 'lomlu',
	'seventeen': 'lompati',
	'fifteen': 'lompin',
	'fourteen': 'lomsna',
	'hundred': 'lomtana',
	'ten': 'lomtiki',
	'thirteen': 'lomtwi',
	'trillion': 'lomtwiti',
	'blood': 'lukia',
	'back': 'mach',
	'earth': 'malnip',
	'pen': 'matcolati',
	'wizard': 'mecroh',
	'cat': 'meooh',
	'squirrel': 'merdushmant',
	'brick': 'mibiywithi',
	'pickaxe': 'michonie',
	'god': 'minstra',
	'human': 'mishnamer',
	'cow': 'molapadi',
	'gram': 'mumuch',
	'clock': 'mytonlesterbont',
	'saxophone': 'namuic',
	'nail': 'nkala',
	'horse': 'nohchi',
	'pig': 'oinch',
	'avacado': 'omaminacink',
	'violin': 'ooopoop',
	'viola': 'oopooop',
	'fight': 'ooth',
	'fire': 'orstanip',
	'finger': 'owseva',
	'fingernail': 'owsevankala',
	'mouth': 'owtater',
	'puddle': 'PHahh',
	'word': 'paglhs',
	'wand': 'pahstah',
	'airplane': 'pateowooshwe',
	'seven': 'patinkao',
	'hair': 'pellacha',
	'five': 'pinlo',
	'game': 'plong',
	'bird': 'poob',
	'flower': 'pritynity',
	'price': 'pru',
	'ocean': 'puntra',
	'sea': 'puntra',
	'bubble': 'puntripol',
	'boat': 'puntrovroom',
	'water': 'putrinp',
	'duck': 'quah',
	'sparkle': 'ricbicyumyumoli',
	'zombie': 'rituy',
	'bee': 'ron',
	'two': 'Ruough',
	'butter': 'sennena',
	'want': 'shaghu',
	'bread': 'shean',
	'like': 'shi',
	'need': 'shighu',
	'toe': 'simbanchi',
	'toenail': 'simbanchinkala',
	'clarinet': 'skrace',
	'turtle': 'sluch',
	'dinosaur': 'snahuah',
	'four': 'snaltiko',
	'nose': 'snipyokyoomyoom',
	'ninja': 'snook',
	'dragon': 'sombanllon',
	'comment': 'spalsplugh',
	'unicorn': 'sparacha',
	'dance': 'spunpindizy',
	'dancer': 'spunpindizy',
	'pear': 'squambuntalbun',
	'fork': 'stah',
	'spork': 'stahuh',
	'tripod': 'staik',
	'knife': 'stoh',
	'storm': 'storum',
	'spoon': 'stuh',
	'base': 'swombar',
	'potato': 'tapadocalinsh',
	'piano': 'tarrrah',
	'rabbit': 'thamin',
	'thunder': 'thracha',
	'bomb': 'timytilest',
	'llama': 'tipee',
	'liter': 'tomufiaci',
	'wall': 'trolipantikomilana',
	'test': 'trong',
	'quiz': 'tronp',
	'sequence': 'twbinein',
	'three': 'twiko',
	'number': 'twinbine',
	'trident': 'twistiyadoi',
	'peanut': 'unatr',
	'favorite': 'voshcha',
	'car': 'vroompater',
	'spy': 'vzklpy',
	'man': 'wah',
	'banana': 'wair',
	'spider': 'wei',
	'trumpet': 'weuh',
	'star': 'wheyowisupo',
	'wind': 'whish',
	'chair': 'whomat',
	'sword': 'woosh',
	'centaur': 'yaklakomlak',
	'noodle': 'yamiron',
	'cake': 'yoomyoom',
	'tree': 'zantampoly'
}

#Checks if the input word is the singular form of a regular plural
def check(word):
	if (regularplurals.count(word) == 1):
		return "true"
	else:
		return "false"

#Checks if the input word is the plural form of a regular plural
def pluCheck(word):
	if (regularplurals.count(word[:len(word) - 1]) == 1):
		return "true"
	else: 
		return "false"

#Returns the singular Spangley equivalent to the input word
def translate(word):
	return trans[word]

#Returns the plural Spangley equivalent to the input word
def pluTrans(word):
	return trans[word[:len(word) - 1]] + 'itt'

#Returns the number of regular plural translation rules present
def wordcount():
	return len(regularplurals)